### ISSUE TITLE
clang-setup script and libdispatch

### ISSUE THREAD

**Issue by digital-pers0n** [gnustep/tools-scripts#5]
Looks like that https://github.com/nickhutchinson/libdispatch repo has been archived and not maintained anymore
The version of libdispatch from here uses <sys/sysctl.h> header which is explicitly marked as deprecated in glibc and will be removed soon.

**Comment by triplef** [comment]
We should probably just be using the official repo https://github.com/apple/swift-corelibs-libdispatch in combination with [this patch](https://raw.githubusercontent.com/gnustep/tools-android/master/patches/libdispatch-own-blocksruntime.patch) from @ngrewe to use the BlocksRuntime from libobjc2.

**Comment by gcasa** [comment]
We are now using the official apple version of this library.
